### ISSUE TITLE
help with execution

### ISSUE THREAD

**Issue by k-nayak** [HemuManju/carla-data-collector#1]
(base) D:\Master Arbeit\TASK\carla-data-collector-master\carla-data-collector-master>python main.py
C:\Users\Keshav\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Keshav\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Users\Keshav\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)
pygame 2.0.1 (SDL 2.0.14, Python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Skipping the block   |  collect_data
Skipping the block   |  parallel_collect_data
Skipping the block   |     read_data

how do i run carla and save the data. It just keeps on skipping. 

Thanks in advance.

**Comment by HemuManju** [comment]
Hi @k-nayak,  just replace the 'skip' keyword with 'run'. It will run that block of code. For example like this.

with skip_run('run', 'collect_data') as check, check():

**Comment by HemuManju** [comment]
I have a added a separate **collect.py** file for collecting the data.
